---
networks:
  mysql-compose-networks: 
    driver: bridge

services:
  adminer: 
    image: adminer
    networks:
      - mysql-compose-networks
    ports:
      - "8080:8080"
    restart: always

  mysqlsrv: 
    command: "--default-authentication-plugin=mysql_native_password"
    environment: 
      MYSQL_DATABASE: "mysqldb"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "admin"
    image: "mysql:8.0.30"
    networks:
      - mysql-compose-networks
    ports:
      -"3300:3300"
    restart: always
    volumes:
      - "/home/VICTPGM:/var/lib/mysql"

version: "3"
