version: '3.5'
services:
    backend: 
      image: image-db
      ports:
        - "80:80"
    MYSQL_DATABASE:
        image: db
        ports:
          - "3306:3036"
        environment:
          MYSQl_ROOT_PASSWORD: Senh@Forte
          MYSQL_DATABASE: image-db
          MYSQL_USER: admin
          MYSQL_PASSWORD: Senh@Forte
        volumes:
        - db-data:var/lib/mysql 

volumes:
  db-data:
