version: '3.5'
services:
    backend: 
      image: image-db
      ports:
        - "80"
    MYSQL_DATABASE:
        image: image-db
        environment:
          MYSQl_ROOT_PASSWORD: Senh@Forte
          MYSQL_DATABASE: image-db
          MYSQL_USER: admin
          MYSQL_PASSWORD: Senh@Forte
        volumes:
          - db-data:var/lib/mysql
        ports:
          - "3306:3036"
volumes:
  db-data:

networks:
  default:
    driver: bridge
