version: '3.5'
services:
    backend: 
      image: mysql-image
      name: mysql-image-name
    MYSQL_DATABASE:
        image: mysql-image
        ports:
          - "3306:3036"
    environment:
        MYSQL_DATABASE: mysql
        MYSQL_USER: admin
        MYSQL_ALLOW_EMPTY_PASSWORD: null
    volumes:
          - db-data:var/lib/mysql
volumes:
  db-data:
